services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://admin:pass1234@mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass1234
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: